steps:
  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/table-communication-app:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/table-communication-app:latest'
      - '.'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/table-communication-app:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'table-communication-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/table-communication-app:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'GOOGLE_AI_API_KEY=${_GEMINI_API_KEY}'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/table-communication-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/table-communication-app:latest'

# Set timeout
timeout: '600s'
